# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/beyondx/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),beyondx)

$(call add-radio-file-sha1-checked,radio/cm.bin_SM-G977B,a9ef9f0e9cf3f168c7aa2772acf510f14e292510)
$(call add-radio-file-sha1-checked,radio/cm.bin_SM-G977N,4ea9638094be00088f4cf426253485fead3d72c5)
$(call add-radio-file-sha1-checked,radio/dqmdbg.img_SM-G977B,914ecd28882ced2d7effb5b6a2f7a1fe4953e88d)
$(call add-radio-file-sha1-checked,radio/dqmdbg.img_SM-G977N,624685259f822fcdfa184a31e79a0b549c180336)
$(call add-radio-file-sha1-checked,radio/keystorage.bin_SM-G977B,2c9276bed63917e3e7ed6347d2057cee77f941a6)
$(call add-radio-file-sha1-checked,radio/keystorage.bin_SM-G977N,c591f43a34de0a1b6974d81987f3a9113602dae4)
$(call add-radio-file-sha1-checked,radio/models,6e52b708d06b9525eef96a6522b48584e837ef75)
$(call add-radio-file-sha1-checked,radio/modem.bin_SM-G977B,3dbc10589dfb9631268180ab4dae29349f34d814)
$(call add-radio-file-sha1-checked,radio/modem.bin_SM-G977N,f2eab863ffc9eec4298c4f478799146dd783d0e4)
$(call add-radio-file-sha1-checked,radio/modem_5g.bin_SM-G977B,2824eea6bba61bf9532f1830275d63a85fbdea2a)
$(call add-radio-file-sha1-checked,radio/modem_5g.bin_SM-G977N,1714cda85955df8d07961a9fedcd86f1d76c1fd4)
$(call add-radio-file-sha1-checked,radio/modem_debug.bin_SM-G977B,0cdd5792efabb052a8bc1037467614ba066383a3)
$(call add-radio-file-sha1-checked,radio/modem_debug.bin_SM-G977N,93ddedb46beda5c3c478515022e17913345eb1de)
$(call add-radio-file-sha1-checked,radio/modem_debug_5g.bin_SM-G977B,ca4e589622492754491d9a4faa38dbc9f157909a)
$(call add-radio-file-sha1-checked,radio/modem_debug_5g.bin_SM-G977N,ba90372feef572d728a21783e7a43f68a198aab9)
$(call add-radio-file-sha1-checked,radio/param.bin_SM-G977B,1443fe5669895a8773f127899b08ed64f3ef658f)
$(call add-radio-file-sha1-checked,radio/param.bin_SM-G977N,75c22f64ab296cc7d3fa032d0f0f026c9186c3ab)
$(call add-radio-file-sha1-checked,radio/sboot.bin_SM-G977B,6ece8668310a734ed5441a2e7e9ff3717d9fd050)
$(call add-radio-file-sha1-checked,radio/sboot.bin_SM-G977N,829fea54768e753eb3315aefa082b4c21fd12184)
$(call add-radio-file-sha1-checked,radio/uh.bin_SM-G977B,311daf1ea991a841c6b4e189455c8244b482ac48)
$(call add-radio-file-sha1-checked,radio/uh.bin_SM-G977N,4da67127cda41e6d84956f6541fe91787a5905a8)
$(call add-radio-file-sha1-checked,radio/up_param.bin_SM-G977B,d2d4f7b06d66eaf4e588a074706bdda6b0a17b96)
$(call add-radio-file-sha1-checked,radio/up_param.bin_SM-G977N,05efa1e59b6fe4d11673429ae5dccbebd6993f5b)
$(call add-radio-file-sha1-checked,radio/version_SM-G977B,c7fdcae6e277d57f648dd37808ae556727058efa)
$(call add-radio-file-sha1-checked,radio/version_SM-G977N,3be1ed16e7d46fdcbca23dc6ee8b435a159dd2e4)

endif
